#!/bin/sh
# dreamreader-sync installer for Debian hosts. Builds and starts the sync service
# (a single Go + SQLite container) and, unless --no-nginx, renders and enables a
# host-Nginx site that proxies the public domain to it.
#
# Identity comes from the IAM platform; deploy that first and register the
# `dream_manga_reader` client as a public client (authorization_code +
# refresh_token + PKCE) with the app's redirect URIs.
#
# Deploy assets (compose, .env, nginx template) live in deploy/install/.
#
# Usage:
#   sudo ./scripts/install.sh                     # interactive setup + install
#   sudo ./scripts/install.sh --setup             # re-run the interactive .env wizard
#   sudo ./scripts/install.sh --no-nginx          # panel manages TLS (aaPanel/BT)
#   ./scripts/install.sh --no-build               # restart only (no rebuild)
#   ./scripts/install.sh --update [--no-pull]     # git pull + rebuild + recreate
set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEPLOY_DIR="$REPO_ROOT/deploy/install"
ENV_FILE="$DEPLOY_DIR/.env"
ENV_EXAMPLE="$DEPLOY_DIR/.env.example"
NGINX_TMPL="$DEPLOY_DIR/nginx-site.conf.tmpl"

DOMAIN=""
DO_NGINX=y
DO_BUILD=y
DO_SETUP=n
UPDATE_MODE=n
DO_PULL=y

c_cyan=$(printf '\033[1;36m'); c_grn=$(printf '\033[1;32m'); c_yel=$(printf '\033[1;33m'); c_red=$(printf '\033[1;31m'); c_off=$(printf '\033[0m')
info() { printf '%s==>%s %s\n' "$c_cyan" "$c_off" "$1"; }
ok()   { printf '%s[ok]%s %s\n' "$c_grn" "$c_off" "$1"; }
warn() { printf '%s[warn]%s %s\n' "$c_yel" "$c_off" "$1" >&2; }
die()  { printf '%s[error]%s %s\n' "$c_red" "$c_off" "$1" >&2; exit 1; }
usage() { sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'; }

# Prompt for a value with a default. $1 var, $2 prompt, $3 default. Assignment
# context suppresses word-splitting so values with special chars survive.
ask() {
  _var=$1; _prompt=$2; _def=${3:-}
  if [ -n "$_def" ]; then printf '    %s\n      [%s]: ' "$_prompt" "$_def"
  else                   printf '    %s\n      : ' "$_prompt"; fi
  IFS= read -r _ans || _ans=""
  [ -z "$_ans" ] && _ans=$_def
  eval "$_var=\$_ans"
}

# Wizard step: how to fetch IAM's JWKS. Sets USE_IAM_NET, JWKS_URI, IAM_NET.
setup_network() {
  USE_IAM_NET=n; JWKS_URI=""; IAM_NET=hertz-iam_default
  printf '\n  JWKS 拉取方式(校验 IAM 令牌签名):\n    1) 走公网 IAM 拉 JWKS(简单)[推荐]\n    2) 加入 IAM 的 Docker 网络,内网拉 JWKS(IAM 与本服务同机 Docker)\n'
  ask _m "选择 1-2" "1"
  case "$_m" in
    1) USE_IAM_NET=n ;;
    2) USE_IAM_NET=y
       ask IAM_NET  "IAM 的 Docker 网络名(docker network ls)" "hertz-iam_default"
       ask JWKS_URI "内网 JWKS URL" "http://iam-api:8080/realms/user/jwks" ;;
    *) die "无效选择: $_m" ;;
  esac
}

# Interactive wizard: collect the essentials and write deploy/install/.env.
setup_env() {
  info "交互式配置(回车=接受 [默认值])"
  ask DOMAIN    "同步服务公网域名 host(如 api.mr.64hz.cn)" "${DOMAIN:-sync.example.com}"
  ask IAM_BASE  "IAM 公网地址 full URL(如 https://account.64hz.cn)" "https://account.example.com"
  ask CLIENT_ID "IAM client_id" "dream_manga_reader"
  ask PORT      "服务 HTTP 端口(本机 127.0.0.1)" "8090"
  ask MAX_DOC   "单文档上限(字节)" "8388608"
  setup_network
  ask GOPROXY   "Go 代理 GOPROXY" "https://goproxy.cn,direct"

  ( umask 077; cat > "$ENV_FILE" <<EOF
# Generated by scripts/install.sh on $(date '+%Y-%m-%d %H:%M:%S'). Edit freely.
HERTZ_GOPROXY=$GOPROXY
HERTZ_BUILD_NETWORK=host
HERTZ_IAM_NETWORK=$IAM_NET

DREAMSYNC_PUBLIC_DOMAIN=$DOMAIN
DREAMSYNC_HTTP_PORT=$PORT
DREAMSYNC_IAM_ISSUER=$IAM_BASE
DREAMSYNC_JWKS_URI=$JWKS_URI
DREAMSYNC_CLIENT_ID=$CLIENT_ID
DREAMSYNC_MAX_DOC_BYTES=$MAX_DOC
DREAMSYNC_CORS_ORIGINS=
DREAMSYNC_USE_IAM_NET=$USE_IAM_NET
EOF
  )
  ok "已写入 $ENV_FILE"
  info "IAM=$IAM_BASE · client=$CLIENT_ID · 端口=$PORT · JWKS=$([ -n "$JWKS_URI" ] && echo "$JWKS_URI" || echo 公网派生) · IAM网络=$USE_IAM_NET"
  warn "别忘了在 IAM 注册 client '$CLIENT_ID'(public + authorization_code + refresh_token + PKCE)与 App 的 redirect_uri。"
}

git_update_repo() {
  info "Updating repository ($REPO_ROOT)"
  [ -d "$REPO_ROOT/.git" ] || { warn "$REPO_ROOT is not a git checkout; skipping pull"; return 0; }
  command -v git >/dev/null 2>&1 || die "git not found; install it or rerun with --no-pull"
  info "current revision: $(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"
  [ -z "$(git -C "$REPO_ROOT" status --porcelain)" ] || die "working tree has local changes; commit/stash or rerun with --no-pull"
  git -C "$REPO_ROOT" pull --ff-only || die "git pull --ff-only failed"
  ok "updated to $(git -C "$REPO_ROOT" rev-parse --short HEAD)"
}

wait_http() {
  _i=0
  while [ "$_i" -lt "$2" ]; do
    if curl -fsS "$1" >/dev/null 2>&1; then return 0; fi
    _i=$((_i + 1)); sleep 1
  done
  return 1
}

# --- args ----------------------------------------------------------------------
while [ $# -gt 0 ]; do
  case "$1" in
    --domain)   DOMAIN="${2:?--domain needs a value}"; shift 2 ;;
    --no-nginx) DO_NGINX=n; shift ;;
    --no-build) DO_BUILD=n; shift ;;
    --setup)    DO_SETUP=y; shift ;;
    --update)   UPDATE_MODE=y; shift ;;
    --no-pull)  DO_PULL=n; shift ;;
    -h|--help)  usage; exit 0 ;;
    *) die "unknown argument: $1 (see --help)" ;;
  esac
done

# --- compose detection ---------------------------------------------------------
if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  die "docker compose not found; install Docker Engine + the compose plugin"
fi
[ -f "$DEPLOY_DIR/docker-compose.yml" ] || die "missing $DEPLOY_DIR/docker-compose.yml"
get_env() { grep -E "^$1=" "$ENV_FILE" 2>/dev/null | head -n1 | cut -d= -f2- ; }

# Layer the IAM-network overlay when the .env selected it. $_f is intentionally
# unquoted to split into -f args; deploy paths have no spaces.
compose() {
  _f="-f $DEPLOY_DIR/docker-compose.yml"
  [ "$(get_env DREAMSYNC_USE_IAM_NET)" = y ] && _f="$_f -f $DEPLOY_DIR/docker-compose.iam-network.yml"
  # shellcheck disable=SC2086
  ( cd "$DEPLOY_DIR" && $COMPOSE $_f --env-file "$ENV_FILE" "$@" )
}

# ===============================================================================
# Update mode: pull + rebuild + recreate. Leaves nginx alone.
# ===============================================================================
if [ "$UPDATE_MODE" = y ]; then
  [ -f "$ENV_FILE" ] || die "$ENV_FILE not found; run a full install before --update"
  PORT="$(get_env DREAMSYNC_HTTP_PORT)"; PORT="${PORT:-8090}"
  if [ "$DO_PULL" = y ]; then git_update_repo; else warn "skipping git pull (--no-pull)"; fi
  info "Building…";   compose build
  info "Recreating…"; compose up -d --force-recreate
  info "Waiting for health…"
  if wait_http "http://127.0.0.1:$PORT/healthz" 30; then ok "healthy on :$PORT"
  else compose logs --tail=80 || true; die "did not become healthy within 30s"; fi
  compose ps
  ok "Update complete."
  exit 0
fi

# ===============================================================================
# Install / redeploy mode.
# ===============================================================================
if [ "$DO_SETUP" = y ] && [ -f "$ENV_FILE" ]; then
  ask _OW "已存在 $ENV_FILE,覆盖? (y/N)" "N"
  case "$_OW" in y|Y) ;; *) info "保留现有 .env,跳过交互配置"; DO_SETUP=n ;; esac
fi
if [ "$DO_SETUP" = y ]; then
  setup_env
elif [ ! -f "$ENV_FILE" ]; then
  if [ -t 0 ]; then
    info "未找到 $ENV_FILE,进入交互式配置(或 Ctrl-C 后手动 cp .env.example .env)"
    setup_env
  else
    [ -f "$ENV_EXAMPLE" ] || die "missing $ENV_EXAMPLE"
    cp "$ENV_EXAMPLE" "$ENV_FILE"
    warn "created $ENV_FILE from the example (non-interactive) — edit it before going live"
  fi
fi

# Pull the public domain from .env when not passed explicitly.
if [ -z "$DOMAIN" ]; then DOMAIN="$(get_env DREAMSYNC_PUBLIC_DOMAIN)"; fi
[ -n "$DOMAIN" ] && [ "$DOMAIN" != "sync.example.com" ] || \
  warn "domain not customized (using '$DOMAIN'); set DREAMSYNC_PUBLIC_DOMAIN or pass --domain"
PORT="$(get_env DREAMSYNC_HTTP_PORT)"; PORT="${PORT:-8090}"

# --- build & start -------------------------------------------------------------
if [ "$DO_BUILD" = y ]; then
  info "Building and starting dreamreader-sync ($COMPOSE)…"
  compose up -d --build
else
  info "Restarting dreamreader-sync (no rebuild)…"
  compose up -d
fi

# --- health probe --------------------------------------------------------------
info "Waiting for health…"
if wait_http "http://127.0.0.1:$PORT/healthz" 30; then
  ok "dreamreader-sync healthy on :$PORT"
else
  warn "did not pass health within 30s; check: $COMPOSE logs dreamreader-sync"
fi

# --- nginx ---------------------------------------------------------------------
if [ "$DO_NGINX" = n ]; then
  info "Skipping Nginx (panel-managed). Reverse-proxy your domain to 127.0.0.1:$PORT."
  info "宝塔/aaPanel 步骤见 deploy/install/README.md(注意把 client_max_body_size 提到 12m)。"
  exit 0
fi
command -v nginx >/dev/null 2>&1 || die "nginx not installed (or use --no-nginx for panel-managed TLS)"
[ "$(id -u)" = 0 ] || die "writing the Nginx site needs root; re-run with sudo (or --no-nginx)"
[ -f "$NGINX_TMPL" ] || die "missing $NGINX_TMPL"

SITE_NAME="dreamreader-sync-$DOMAIN"
SITE_AVAIL="/etc/nginx/sites-available/$SITE_NAME.conf"
info "Rendering Nginx site $SITE_AVAIL"
sed -e "s/__DOMAIN__/$DOMAIN/g" -e "s/__SYNC_PORT__/$PORT/g" "$NGINX_TMPL" > "$SITE_AVAIL"
if [ -d /etc/nginx/sites-enabled ]; then
  ln -sf "$SITE_AVAIL" "/etc/nginx/sites-enabled/$SITE_NAME.conf"
else
  warn "no /etc/nginx/sites-enabled; include $SITE_AVAIL from your nginx.conf manually"
fi
info "Testing Nginx config…"; nginx -t
if command -v systemctl >/dev/null 2>&1; then systemctl reload nginx; else nginx -s reload; fi

ok "Done. http://$DOMAIN -> dreamreader-sync (:$PORT)."
info "Re-deploy after changes:  ./scripts/install.sh --update"
if command -v certbot >/dev/null 2>&1; then
  warn "Enable HTTPS: certbot --nginx -d $DOMAIN"
else
  warn "certbot not installed; install it and run: certbot --nginx -d $DOMAIN"
fi
